# example service that is routed through Internal Traefik
services:
  echo:
    image: mendhak/http-https-echo:36
    networks:
      - public_web
    labels:
      traefik.enable: true
      traefik.http.routers.echo1.rule: Host(`echo1.CHANGEME.com`)
      traefik.http.services.echo1.loadbalancer.server.port: 8080
      traefik.docker.network: public_web
      kop.namespace: public
networks:
  public_web:
    external: true